services:
  django-oauth:
    container_name: "django_oauth_vsb"
    build:
      context: "./django-oauth-vsb"
    volumes:
      - "./django-oauth-vsb:/app"
    networks:
      - ip6net
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vsbdjango.rule=Host(`oauth2-vsbproject.imateapot418.tech`)"
      - "traefik.http.services.vsbdjango.loadbalancer.server.port=9999"
    environment:
      - "DJANGO_OAUTH_HOST=oauth2-vsbproject.imateapot418.tech"
      - "GUNICORN_PORT=9999"
      - "DJANGO_DEBUG=1"

  nginx:
    container_name: "nginx"
    build:
      context: "./nginx"
    volumes:
      - "./nginx/config:/etc/nginx:ro"
      - "./django-oauth-vsb/src/oauth2-django-vsb/staticfiles:/data/www"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.imateapot418.tech`) || (Host(`oauth2-vsbproject.imateapot418.tech`) && PathPrefix(`/static`))"
      - "traefik.http.services.nginx.loadbalancer.server.port=9998"
    depends_on:
      - django-oauth
    networks:
      - ip6net
      - proxy
